### ISSUE TITLE
[21/08/19] TODO 

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#1]
- [x] github 사용법 배우기
- [x] 유니티 이용한 게임 개발 예제 따라하기
- [x] sourcetree 익히기
- [x] 6시 송도 약속
- [x] 영상 편집 준비(자캐,자막바)
- [x] QT
