### ISSUE TITLE
[21/10/05]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#28]
- [ ] QT
- [ ] 파이썬 게임 개발 강의 듣기
- [ ] 파이썬 게임 개발 따라하기
- [ ] 5시 수업
- [ ] 머리자르기
- [ ] 이것이 코딩테스트다 강의
