### ISSUE TITLE
[21/10/15]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#33]
- [x] QT
- [x] 전기기사 회로이론 강의 4
- [x] 전기기사 회로이론 강의 5
- [x] 자전거 타고 송도 왕복
- [x] 3시 약속
- [x] python 게임 디테일 구현
