### ISSUE TITLE
[21/10/18]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#34]
- [x] QT
- [x] 노트북 듀얼모니터 설정
- [x] 게임 구체적인 작동 기획
- [x] 회로이론 강의 ch02 끝내기
- [x] 회로이론 노트 정리
- [x] 중2,중3 수업준비
