### ISSUE TITLE
[21/10/21]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#36]
- [x] QT
- [x] 책상 배치 변경
- [x] 책장 뒷면 시트지 붙이기
- [x] 회로이론 ch04 강의
- [x] ch04 노트정리
- [ ] 프로젝트 구상
- [x] 노트북 유니티 환경 구축
- [x] 또 뭐하지?
