### ISSUE TITLE
[21/10/26]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#38]
- [x] QT
- [x] 회로 이론 ch06 강의
- [x] ch06 노트 정리
- [ ] pygame 충돌 처리
- [x] 유니티 예제 따라하기
- [x] 5시 수업
