### ISSUE TITLE
[21/10/29]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#40]
- [x] QT
- [x] QT한거 리더방에 정리해서 공유
- [x] 3시쯤 약속
- [x] 유니티 예제 따라하기
- [x] pygame 예제 따라하기
- [x] 회로이론 8장
- [ ] (시간남으면 9장까지) 수목 못한거 ㅜ
- [x] 9시 기도회
- [x] 중3 아이들 보강 잡기

**Comment by kimdae-1** [comment]
유니티 예제 따라하기 -> 노트북에서 데스크탑으로 데이터 옮겨서 예제 진행하기
