### ISSUE TITLE
[21/11/01]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#41]
- [x] QT
- [x] 7시 축구
- [x] 3시 공부 카페
- [x] 회로 이론 ch 08
- [x] ch 08 노트 정리
- [x] pygame 완성
- [ ] 노트북 -> 컴퓨터 유니티 게임 옮기기
