### ISSUE TITLE
[21/11/02]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#42]
- [x] QT
- [x] 11시 약속
- [ ] 5시 출근
- [x] 회로이론 ch09
- [x] ch09 노트 정리
- [x] pygame 활용해서 나만의 게임 구상
- [x] 나만의 게임 틀잡기
