### ISSUE TITLE
[21/11/08]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#44]
- [x] QT
- [x] 회로이론 ch 10 강의 듣기
- [x] ch 10 노트 정리
- [x] pygame 정리
- [x] 수업준비
- [x] 10시 약속
- [ ] pygame 쓰일 캐릭터, 배경, 적 그리기
