### ISSUE TITLE
[21/11/09]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#45]
- [x] QT
- [ ] 회로 이론 ch 11 강의 듣기
- [ ] ch 11 노트 정리
- [ ] pygame 충돌~
- [ ] pygame에 필요한 이미지들 만들기
