### ISSUE TITLE
[21/11/10]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#46]
- [x] QT
- [x] 회로 이론 ch 11 강의 듣기
- [x] ch 11 노트 정리
- [x] 장구 키트 구멍 뚫기
- [x] 이터널스 보기
- [ ] 영상 녹화
- [x] pygame 충돌~ 
- [ ] pygame 필요한 이미지 제작
- [x] 수업 준비
