### ISSUE TITLE
[21/11/11]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#47]
- [x] QT
- [x] 회로 이론 ch 12 강의 듣기
- [x] ch 12 노트 정리
- [x] pygame 게임 종료 문구 띄우기
- [ ] pygame에 필요한 이미지 제작
- [x] 5시 수업
