### ISSUE TITLE
[21/11/15]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#49]
- [x] QT
- [x] 회로이론 ch 13 강의 듣기
- [x] ch 13 노트 정리
- [x] 6시 약속
- [x] 전기기사 책
- [x] 이미지 제작
- [x] 영상 녹화
- [x] 제어공학 OT ch01
- [x] 전기기사 회로이론 문제 풀어보기
