### ISSUE TITLE
[21/08/23]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#5]
- [x] QT
- [x] 코딩테스트 Ch03
- [x] 코딩테스트 Ch03 예제 풀고 github commit 하기
- [x] c++강의 2개 듣고 따라하기
- [x] 영상 소스 다운
- [x] 과학 수업 준비
- [x] 방청소
