### ISSUE TITLE
[21/11/18]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#51]
- [x] QT
- [x] 제어 공학 ch 02 강의 듣기
- [x] ch 02 노트 정리
- [x] 회로 이론 문제 풀기
- [x] 자전거 송도 왕복
