### ISSUE TITLE
[21/12/02]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#53]
- [x] QT
- [x] 제어공학 ch 05 강의듣기
- [x] ch 05 노트정리
- [x] 21년 2회차 회로이론 문제 풀기
- [x] 회로이론 복습하기 ( ch 01- 03 )
