### ISSUE TITLE
[21/12/03]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#54]
- [x] QT
- [x] 제어공학 ch 06 강의 듣기
- [x] ch 06 노트정리
- [ ] 20년 06월 전기기사 회로이론 문제 풀기
- [ ] 회로이론 ch 04 - ch 06 복습
- [ ] 파이썬 강의 찾아보기
