### ISSUE TITLE
[21/12/06]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#55]
- [x] QT
- [x] 제어 공학 ch 07
- [x] ch 07 노트 정리
- [x] 20년 06월 제어&회로 이론 풀기
- [x] 중3 - 물리, 중2 - 시험 준비
- [ ] 영상 편집
