### ISSUE TITLE
[21/12/08]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#56]
- [x] QT
- [x] 제어 공학 ch 08 강의 듣기
- [x] ch 08 노트 정리
- [x] 19년 08월 제어 + 회로 문제 풀기
- [x] 송사비의 클래식 음악 야화 ch2 읽기
