### ISSUE TITLE
[21/12/09]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#57]
- [x] QT
- [x] 전기자기학 ch 01 강의 듣기
- [x] ch 01 노트 정리
- [x] 20년 09월 제어 & 회로 문제 풀고 정리
- [ ] 송사비의 클래식 음악야화 ch 03 읽기
