### ISSUE TITLE
[21/12/10]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#58]
- [x] QT
- [x] 전기자기학 ch 02 -1 강의 듣기
- [x] ch 02 -1 노트 정리
- [ ] 21년 03월 제어 회로
- [x] 종이의 집 시즌 5
- [x] 7시 약속
- [ ] 송사비의 음악야화 ch03 읽기
