### ISSUE TITLE
[21/12/11]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#59]
- [x] QT
- [x] 전기자기학 ch 02 -2 강의
- [x] ch 02 노트 정리
- [x] 송사비의 클래식 음악야화 ch 03-1 읽기
- [x] 5시 약속
