### ISSUE TITLE
[21/12/15]TODO List

### ISSUE THREAD

**Issue by kimdae-1** [kimdae-1/ToDoList#62]
- [x] QT
- [x] 전기자기학 ch 03 -1 강의 듣기
- [x] ch 03 -1 노트 정리
- [x] 21년 05월 제어&회로 문제 풀이
- [x] 리더나눔지_5순_김대원 - 6시
- [x] 9시10분 약속
